---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: basicapi-deployment
spec:
  selector:
    matchLabels:
      app: basicapi
  replicas: 2
  template:
    metadata:
      labels:
        app: basicapi
    spec:
      containers:
      - name: basicapi
        image: thatsk/basicapi:dev
        ports:
        - containerPort: 3500
